[package]
name = "solaris-graphics"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.99"
ash = { version = "0.38.0" }
ash-window = { version = "0.13.0" }
once_cell = "1.21.3"
winit = "0.30.12"
